name: Prevent upmerges from being squash merged

on:
  merge_group:
    types: [checks_requested]
  # Necessary, otherwise PRs will have a "pending" check that will never resolve
  pull_request:

jobs:
  no-upmerge-squash:
    name: Prevent upmerges from being squash merged
    runs-on: ubuntu-latest
    # Makes sure this check just gets cancelled while in a PR
    if: github.event_name == 'merge_group'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
        with:
          # Always has to be bigger than the maximum queue size
          fetch-depth: 10

      - name: Check commit titles
        env:
          BASE_SHA: ${{ github.event.merge_group.base_sha }}
          HEAD_SHA: ${{ github.event.merge_group.head_sha }}
        run: |
          # Get commit title between master and queue head
          COMMIT_TITLES=$(git log --format=%s $BASE_SHA..$HEAD_SHA)

          # Regex pattern to be run against a lowercase version of the commit titles. Can be expanded as needed
          PATTERN="upmerge"
          
          if [[ "${COMMIT_TITLES,,}" =~ $PATTERN ]]; then
            echo "::error title=Upmerge detected::Mention of an upmerge was found in this merge queue group."
            exit 1
          fi
